### ISSUE TITLE
iOS 14.2 App-Prefs:root=CASTLE and App-Prefs:root=CASTLE and &path=BACKUP not working

### ISSUE THREAD

**Issue by pistoleta** [FifiTheBulldog/ios-settings-urls#2]
I've tried these 2 and both bring me to the general settings window. 
Is it normal ?

**Comment by FifiTheBulldog** [comment]
Use `prefs` instead of `app-prefs` for the URL scheme.

**Comment by pistoleta** [comment]
> Use `prefs` instead of `app-prefs` for the URL scheme.

`prefs`  does't open anything, CanOpenURL() returns false.

The only way I get it do open the settings is using App-Prefs, but as I said, I just see the general settings dialog.

**Comment by pistoleta** [comment]
https://stackoverflow.com/questions/40365721/how-to-open-icloud-settings-through-app

Here they say it's not supported, the post is quite old so I was hoping accessing  to the iCloud settings was supported already since its mandatory for using CloudKit and other tools.

**Comment by FifiTheBulldog** [comment]
That's odd. When I open `prefs` URLs through Shortcuts (on both iOS 13 and 14), they work perfectly. But when I try to open any Settings URL through Safari, even after testing it several times in Shortcuts and working every time, it fails. (I actually designed this list for Shortcuts users, so that's what I've been using to test. Shortcuts is a very forgiving app.)

Maybe Apple has placed artificial restrictions on opening Settings URLs? I don't know.

I tried using an x-callback URL trick where it assigns the URL you want to the x-error parameter and then goes through Shortcuts but intentionally gives an error. I've seen that used in shortcuts like Icon Themer to get around otherwise restricted URL schemes. However, that only opens the Settings app, rather than taking me to the page I want. So that's a dead end.

**Comment by pistoleta** [comment]
I dont really know how this ShortCuts thing works but is it possible to set the iCloud setting shortcut in it from my app and use it?  I guess not.

**Comment by FifiTheBulldog** [comment]
I actually don't know. Truth be told, I know almost nothing about iOS app development (I can put together a sample app from a tutorial, but that's about it). However, I don't think apps are allowed to change iCloud settings, if those are supposed to be strictly user-controlled.

**Comment by pistoleta** [comment]
I don't want to change iCloud settings actively, but to bring the user to the iCloud settings window. Where he can enable disable by himself.
Anyway Im quite sure it's not possible. 
Thanks anyway

**Comment by FifiTheBulldog** [comment]
Did you ever get this to work? I found that the scheme `App-prefs:` (capital A, lowercase p) worked flawlessly when opening Settings URLs from [Scriptable](https://scriptable.app). I'm curious whether the same goes for opening URLs from Swift in an app.

(Of course, there's still the issue of Apple barring apps that use any of these URLs from being on the App Store, but ignoring that...)

**Comment by pistoleta** [comment]
> Did you ever get this to work? I found that the scheme `App-prefs:` (capital A, lowercase p) worked flawlessly when opening Settings URLs from [Scriptable](https://scriptable.app). I'm curious whether the same goes for opening URLs from Swift in an app.
> 
> (Of course, there's still the issue of Apple barring apps that use any of these URLs from being on the App Store, but ignoring that...)

Hi there, from beginning I was able to open general settings. But what I was tryin to open were the iCloud settings, (thats what's supposed to mean "CASTLE and &path=BACKUP"  if I remember correctly.
I finally went to some forum post in the apple developer site and found it was not allowed.
An app is just supposed to open it's own app settings and the general settings, but not other app's settings or iCloud settings which is what I wanted.
Did you manage to open iCloud settings with this Scriptable thing?

**Comment by FifiTheBulldog** [comment]
Actually, I take that back. I just tried that URL with Scriptable, and it just brought me to the Settings app without navigating. Perhaps I mistook opening the app for opening a specific page in my limited testing? I could have sworn...but apparently not.

So it seems that only Shortcuts can actually use these links and have Settings navigate to the requested page. All other apps must be restricted to whatever APIs Apple makes available to them and are unable to just navigate to wherever they want in Settings. (Unless they run a shortcut by x-callback URL, which does nothing for most apps since it requires the user to set that up.) Interesting.
