### ISSUE TITLE
Able to submit to app store when using these shortcuts?

### ISSUE THREAD

**Issue by formaldehydeson** [FifiTheBulldog/ios-settings-urls#9]
Has anybody recently submitted an app that is using one of these settings shortcuts to the app store? I'm seeing a lot of talk of Apple rejecting apps that are using this URL scheme from around 2018-2019 so I'm wondering if that's still the case today

**Comment by FifiTheBulldog** [comment]
That’s definitely still the case today. Technically these are still a private API, meaning they could change at any time, and Apple hasn’t gotten any more accepting of people using private APIs in their apps.

In fact, @ActuallyZach even tried opening these URLs in both Swift and Objective-C, and they didn’t work; they just took him to the main page of the Settings app, rather than to the desired subpages. So not only is there an App Store review restriction, there’s also a (rather artificial) software limitation that makes it hard to even get to App Review with a working app that uses these URLs.

There might be a way to simulate being a system app, which seems like it would allow you to open Settings URLs normally, but that would *definitely* get rejected. It can also be done (sort of) with the x-callback-url scheme for Shortcuts, but it relies on Shortcuts being installed and doesn’t open all URLs.

I suppose you could try to submit to the App Store if you can get these URLs working, but I’m 99% sure it’ll get rejected.

**Comment by ahrendsen** [comment]
Hi @formaldehydeson,

Since your question has been answered, can you please close this issue? Just trying to do my part to keep this awesome resource tidy and up-to-date.

Thanks,
Karl
